name: Auto Hindi Shorts

on:
  workflow_dispatch:   # ðŸ‘ˆ YE LINE ADD KARO
  schedule:
    - cron: '0 3 * * *'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python generate_script.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
      - run: python generate_voice.py
      - run: python generate_video.py
      - run: python upload_youtube.py
        env:
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
